vs2022/starwars-game/starwars.game.Web.UI/Models/ErrorViewModel.cs
namespace starwars.game.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/GameListViewModel.cs
using game.api;

namespace starwars.game.Web.UI.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class GameListViewModel
    {
        public List<Game> GameList { get; set; } = new();
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/GameController.cs
using game.api;
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Infrastructures;
using starwars.game.Web.UI.Models;

namespace starwars.game.Web.UI.Controllers
{
	public class GameController : Controller
	{
		public IActionResult Index()
		{
			var sauvegardeur = new BddGameSauvegarde();

			List<Game> games = new()
			{
				new(sauvegardeur) { Id = 1, CheckPointList = new() { new(1, 150) } },
				new(sauvegardeur) { Id = 2, CheckPointList = new() { new(2, 200) } }
			};

			return View(new GameListViewModel()
			{
				GameList = games
			});
		}
	}
}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Models;
using System.Diagnostics;

namespace starwars.game.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Views/Game/Index.cshtml
@using game.api
@model GameListViewModel

<table class="table">
	<thead>
		<tr>
			<th>
				Id
			</th>
			<th>
				Date
			</th>
			<th>
				CheckPoints
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var game in Model.GameList)
		{
			<tr>
				<td>@game.Id</td>
				<td>@game.DateDebut.ToString("dddd dd MMMM yyyy")</td>
				<td></td>
			</tr>
		}
	</tbody>
</table>

vs2022/starwars-game/starwars.game.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

vs2022/starwars-game/starwars.game.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - starwars.game.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/starwars.game.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">starwars.game.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Parties</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - starwars.game.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>